"""Install the Dao-KiCad action plugin into KiCad's plugin search path.

KiCad scans ``<KiCad documents>/<ver>/scripting/plugins`` (and ``3rdparty``)
and imports every module it finds there. We drop a one-line shim that calls
:func:`daokicad.kicad_plugin.register`, so the real plugin code lives in the
installed ``daokicad`` package (editable-installed into KiCad's Python) and the
shim never goes stale.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

_SHIM = '''# Auto-generated by `daokicad install-plugin`. Do not edit.
# Loads the Dao-KiCad action plugin from the installed `daokicad` package.
try:
    from daokicad.kicad_plugin import register
    register()
except Exception:  # surface import/registration errors in KiCad's log
    import traceback
    traceback.print_exc()
'''


def _kicad_version() -> str:
    """Best-effort 'major.minor' KiCad version (e.g. '10.0')."""
    try:
        import pcbnew
        parts = pcbnew.Version().split(".")
        return ".".join(parts[:2])
    except Exception:
        try:
            from .. import env
            v = (env.detect().version or "").split(".")
            if len(v) >= 2:
                return ".".join(v[:2])
        except Exception:
            pass
    return "10.0"


def default_plugins_dir() -> Path:
    """The user 'scripting/plugins' dir for the detected KiCad version."""
    docs = os.environ.get("KICAD_DOCUMENTS_HOME")
    base = Path(docs) if docs else (Path.home() / "Documents" / "KiCad")
    return base / _kicad_version() / "scripting" / "plugins"


def install(dest: Optional[str | Path] = None) -> dict:
    """Write the shim into the plugins dir. Returns a small status dict."""
    plugins = Path(dest) if dest else default_plugins_dir()
    plugins.mkdir(parents=True, exist_ok=True)
    shim = plugins / "dao_kicad_plugin.py"
    shim.write_text(_SHIM, encoding="utf-8")
    return {"ok": True, "shim": str(shim), "plugins_dir": str(plugins),
            "kicad_version": _kicad_version()}
